import { Route } from "./RouteCard";

export const routes: Route[] = [
  {
    id: "1",
    name: "Тюмень - Тобольск",
    description:
      "Живописный маршрут до исторического города Тобольска через малые города и села.",
    distance: 247,
    duration: "3.5 часа",
    difficulty: "easy",
    type: "scenic",
    startPoint: "Тюмень, Центральная площадь",
    endPoint: "Тобольск, Кремль",
    waypoints: ["Ярково", "Аромашево", "Вагай"],
    highlights: ["Тобольский кремль", "Иртыш", "Исторические места"],
    surface: "asphalt",
    season: "all",
    rating: 4.8,
    reviewCount: 34,
    createdBy: "Александр Путешественник",
    images: ["https://picsum.photos/400/300?random=50"],
  },
  {
    id: "2",
    name: "Кольцо Заречного",
    description:
      "Городской маршрут вокруг Заречного района с посещением интересных мест.",
    distance: 45,
    duration: "1.5 часа",
    difficulty: "easy",
    type: "city",
    startPoint: "Тюмень, мост Влюбленных",
    endPoint: "Тюмень, набережная",
    waypoints: ["Заречный парк", "Озеро Андреевское"],
    highlights: ["Парки", "Набережная", "Озера"],
    surface: "asphalt",
    season: "all",
    rating: 4.3,
    reviewCount: 18,
    createdBy: "Городской райдер",
    images: ["https://picsum.photos/400/300?random=51"],
  },
  {
    id: "3",
    name: "Горячие источники",
    description:
      "Маршрут к горячим источникам с возможностью отдыха и купания.",
    distance: 89,
    duration: "2 часа",
    difficulty: "medium",
    type: "adventure",
    startPoint: "Тюмень",
    endPoint: 'Источники "Сосновый бор"',
    waypoints: ["Каменка", "Богандинка"],
    highlights: ["Горячие источники", "Сосновый лес", "Отдых"],
    surface: "mixed",
    season: "all",
    rating: 4.6,
    reviewCount: 27,
    createdBy: "Любитель природы",
    images: ["https://picsum.photos/400/300?random=52"],
  },
  {
    id: "4",
    name: "Спортивный серпантин",
    description:
      "Извилистый маршрут для любителей активной езды с множеством поворотов.",
    distance: 67,
    duration: "2.5 часа",
    difficulty: "hard",
    type: "sport",
    startPoint: "Тюмень, Парковая зона",
    endPoint: "Возвращение к старту",
    waypoints: ["Винзили", "Перевалово", "Богандинка"],
    highlights: ["Серпантин", "Холмы", "Виды"],
    surface: "asphalt",
    season: "spring-autumn",
    rating: 4.9,
    reviewCount: 15,
    createdBy: "Спортивный байкер",
    images: ["https://picsum.photos/400/300?random=53"],
  },
  {
    id: "5",
    name: "Лесными тропами",
    description: "Приключенческий маршрут по лесным дорогам и тропам.",
    distance: 123,
    duration: "4 часа",
    difficulty: "hard",
    type: "adventure",
    startPoint: "Тюмень",
    endPoint: "Лесное озеро",
    waypoints: ["Рощино", "Лесная база", "Кордон"],
    highlights: ["Дикая природа", "Озеро", "Лесные тропы"],
    surface: "gravel",
    season: "summer",
    rating: 4.7,
    reviewCount: 22,
    createdBy: "Адвенчур гид",
    images: ["https://picsum.photos/400/300?random=54"],
  },
];
